<?php
// public/setup_db.php
require_once '../config/db.php';

// Turn off foreign key checks
$pdo->exec("SET FOREIGN_KEY_CHECKS = 0");

$sql = file_get_contents('../database/schema.sql');

if (!$sql) {
    die("Error: Could not read schema.sql");
}

try {
    // 1. Run the raw SQL Schema (Creates tables)
    $pdo->exec($sql);

    // 2. Clear any data that might have been inserted by the SQL file
    $pdo->exec("TRUNCATE TABLE users");
    $pdo->exec("TRUNCATE TABLE cases");
    $pdo->exec("TRUNCATE TABLE criminals");
    $pdo->exec("TRUNCATE TABLE evidence");

    // 3. Seed Users with CORRECT hashes generated by this server
    echo "Seeding users...<br>";

    $password = 'password123';
    $hash = password_hash($password, PASSWORD_DEFAULT);

    $users = [
        ['admin', 'admin@crms.local', $hash, 'admin', 'System Administrator'],
        ['officer1', 'officer@crms.local', $hash, 'officer', 'Officer John Doe'],
        ['detective1', 'detective@crms.local', $hash, 'detective', 'Detective Sherlock'],
        ['forensics1', 'lab@crms.local', $hash, 'forensics', 'Dr. Watson']
    ];

    $stmt = $pdo->prepare("INSERT INTO users (username, email, password_hash, role, full_name) VALUES (?, ?, ?, ?, ?)");

    foreach ($users as $user) {
        $stmt->execute($user);
    }

    echo "<h1 style='color:green'>Database Setup & Seeding Complete!</h1>";
    echo "<p>Users have been re-created with valid password hashes.</p>";
    echo "<h3>Login Credentials:</h3>";
    echo "<ul>
            <li><strong>Username:</strong> admin</li>
            <li><strong>Password:</strong> password123</li>
          </ul>";
    echo "<br><a href='login.php'>Go to Login Page</a>";

} catch (PDOException $e) {
    echo "<h1 style='color:red'>Setup Failed</h1>";
    echo "<p>Error: " . $e->getMessage() . "</p>";
}

$pdo->exec("SET FOREIGN_KEY_CHECKS = 1");
?>