<?php
session_start();
if (!isset($_SESSION['user_id'])) {
    header("Location: login.html");
    exit();
}
include 'db_connection.php';

// Fetch all reports from the database
$sql = "SELECT * FROM Reports ORDER BY created_at DESC";  // Assuming `created_at` column exists
$result = $conn->query($sql);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Reports - Criminal Records Management System</title>
    <link rel="stylesheet" href="view_reports.css">
</head>
<body>
    <div class="report-container">
        <h1>Generated Reports</h1>

        <?php if ($result->num_rows > 0): ?>
            <table>
                <thead>
                    <tr>
                        <th>Report Name</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php while ($row = $result->fetch_assoc()): ?>
                        <tr>
                            <td><?php echo htmlspecialchars($row['report_name']); ?></td>
                            <td><?php echo htmlspecialchars($row['generated_by']); ?></td>
                            <td><?php echo date('Y-m-d H:i:s', strtotime($row['created_at'])); ?></td>
                            <td>
                                <a href="view_report_details.php?report_id=<?php echo $row['report_id']; ?>">View Details</a>
                            </td>
                        </tr>
                    <?php endwhile; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p>No reports generated yet.</p>
        <?php endif; ?>

        <a href="dashboard.php">Back to Dashboard</a>
    </div>
</body>
</html>
